### ISSUE TITLE
Test algorithms in real machines

### ISSUE THREAD

**Issue by BrunoRosendo** [BrunoRosendo/master-thesis#44]
# Things to do

## DWave:
- [x] Test more samplers, I only used the hybrid for CQM
- [x] Increase the input and record the execution times to understand the possible problem size (after #76 and #74)
- [x] Understand why max min_time is always 5 secs, this is not representative of the input size (hard values that can be verified in the list of solvers under the dashboard)
- [x] Understanding the charge times (related to #12)

## Qiskit:
- [x] Investigate why IBM-Q takes so long with so many iterations, even small problems are impossible (compare iterations with classic optimizer) -> locally there are also a lot of iterations, it's just the session problem
- [x] Investigate why multiple jobs are being created. A session might be needed
- [x] Increase the input and record the execution times to understand the possible problem size
- [x] Try to re-submit the extra credits form? I'm not getting a response...
- [x] Create a way to read an env var or a configuration file instead of pasting the hard coded token

**Comment by BrunoRosendo** [comment]
DWave ran seamlessly by simply using the LeapHybridCQMSampler instead of the exact solver. This was the input:

```python
cvrp = DWaveSolver(
        2,
        None,
        [
            (456, 320),
            (228, 0),
            (912, 0),
            (0, 80),
            # (114, 80),
            # (570, 160),
            # (798, 160),
            # (342, 240),
            # (684, 240),
            # (570, 400),
            # (912, 400),
            # (114, 480),
            # (228, 480),
            # (342, 560),
            # (684, 560),
            # (0, 640),
            # (798, 640),
        ],
        [
            (2, 1, 6),
            (3, 0, 5),
        ],
        True,
        True,
        sampler=LeapHybridCQMSampler(),
    )
```

the problem ID was 53b3f708-20dd-4a6f-8313-929b5f7161d1

**Comment by BrunoRosendo** [comment]
The same problem would approximately take 7min on ibm_osaka, so I cancelled it... Idk why it would take so long, I need to investigate

Even the small problem below takes too long. IBM is also creating multiple jobs to run the algorithm.

```python
if __name__ == "__main__":
    # load account, the API key is a placeholder
    IBMQ.save_account(
        "TOKEN"
        overwrite=True,
    )
    IBMQ.load_account()
    provider = IBMQ.get_provider(hub="ibm-q")
    backend = provider.get_backend("ibm_osaka")

    cvrp = CplexSolver(
        1,
        None,
        [
            (456, 320),
            (228, 0),
            # (912, 0),
            # (0, 80),
            # (114, 80),
            # (570, 160),
            # (798, 160),
            # (342, 240),
            # (684, 240),
            # (570, 400),
            # (912, 400),
            # (114, 480),
            # (228, 480),
            # (342, 560),
            # (684, 560),
            # (0, 640),
            # (798, 640),
        ],
        [
            (0, 1, 6),
        ],
        True,
        sampler=BackendSampler(backend),
    )
    result = cvrp.solve()
    result.display()
```

**Comment by BrunoRosendo** [comment]
# Things to do

## DWave:
- [ ] Test more samplers, I only used the hybrid for CQM
- [ ] Increase the input and record the execution times to understand the possible problem size
- [ ] Understanding the charge times (related to #12)

## IBM
- [ ] Investigate why IBM-Q takes so long with so many iterations, even small problems are impossible
- [ ] Investigate why multiple jobs are being created. A session might be needed
- [ ] Increase the input and record the execution times to understand the possible problem size
- [ ] Try to re-submit the extra credits form? I'm not getting a response...

**Comment by BrunoRosendo** [comment]
On DWave, the hybrid solver executed up to the time limit. I will try with a lower time limit and other solvers

**Comment by BrunoRosendo** [comment]
The minimum time limit is 5 seconds (the default), so we cannot lower it. The explanation is here https://dwave-systemdocs.readthedocs.io/en/latest/reference/generated/dwave.system.samplers.LeapHybridSampler.sample.html

Maximum run time, in seconds, to allow the solver to work on the problem. Must be at least the minimum required for the number of problem variables, which is calculated and set by default. The minimum time for a hybrid solver is specified as a piecewise-linear curve defined by a set of floating-point pairs, the minimum_time_limit field under [properties](https://dwave-systemdocs.readthedocs.io/en/latest/reference/generated/dwave.system.samplers.LeapHybridSampler.properties.html#dwave.system.samplers.LeapHybridSampler.properties). The first element in each pair is the number of problem variables; the second is the minimum required time. The minimum time for any particular number of variables is a linear interpolation calculated on two pairs that represent the relevant range for the given number of variables. For example, if LeapHybridSampler().properties[“minimum_time_limit”] returns [[1, 0.1], [100, 10.0], [1000, 20.0]], then the minimum time for a 50-variable problem is 5 seconds, the linear interpolation of the first two pairs that represent problems with between 1 to 100 variables.

**Comment by BrunoRosendo** [comment]
There is a way to convert CQM to BQM, just like mentioned in #74. I will now try to run with that instead of CQM hybrid solver (the problem is the same):

- *Local solver:* works well and gives the right solution
- *Hybrid sampler*: the solution is correct and the execution time was 3 instead of 5 (because of lower time_limit)
- *DWave sampler*: the solution is incorrect but the execution time was only the qpu access time (15ms). This is very promising if I can fix the results. SOLVED -> the problem was the num_reads parameter, the default for this sampler is 1. I set it to 5000 and got the solution for 588ms with 5000 reads (this value should probably be lowered)

My conclusion with these experiments is that I need to support BQM conversion to use samplers simpler than LeapHybridCQM, so I bumped the priority of #74. Then, I can decide which sampler to use based on the input size, by balancing best solution (hybrid) and execution time (quantum only)

**Comment by BrunoRosendo** [comment]
There was an error solving a problem with more than 32 variables so I created #76

**Comment by BrunoRosendo** [comment]
I ran this example (510 vars) with leap's hybrid cqm sampler, and the result was fantastic. It still took 5 seconds

```python
cvrp = DWaveSolver(
        2,
        None,
        [
            (456, 320),
            (228, 0),
            (912, 0),
            (0, 80),
            (114, 80),
            (570, 160),
            (798, 160),
            (342, 240),
            (684, 240),
            (570, 400),
            (912, 400),
            (114, 480),
            (228, 480),
            (342, 560),
            (684, 560),
            (0, 640),
            (798, 640),
        ],
        [
            (1, 6, 5),
            (2, 10, 6),
            (4, 3, 4),
            (5, 9, 2),
            (7, 8, 7),
            (15, 11, 4),
            (13, 12, 6),
            (16, 14, 4),
        ],
        True,
        True,
        sampler=LeapHybridCQMSampler(),
    )
```

This is very promising

**Comment by BrunoRosendo** [comment]
Another input, this time with 1020 variables (still 5 secs):

```python
cvrp = DWaveSolver(
        4,
        10,
        [
            (456, 320),
            (228, 0),
            (912, 0),
            (0, 80),
            (114, 80),
            (570, 160),
            (798, 160),
            (342, 240),
            (684, 240),
            (570, 400),
            (912, 400),
            (114, 480),
            (228, 480),
            (342, 560),
            (684, 560),
            (0, 640),
            (798, 640),
        ],
        [
            (1, 6, 5),
            (2, 10, 6),
            (4, 3, 4),
            (5, 9, 2),
            (7, 8, 7),
            (15, 11, 4),
            (13, 12, 6),
            (16, 14, 4),
        ],
        True,
        True,
        sampler=LeapHybridCQMSampler(),
    )
```

![image](https://github.com/BrunoRosendo/master-thesis/assets/55768934/e2154dbd-4579-4e30-8c6a-c6c91c315f93)

**Comment by BrunoRosendo** [comment]
> Another input, this time with 1020 variables (still 5 secs). This solution does not satisfy all the trips, but it's likely a matter of increasing the time limit
> 
> ```python
> cvrp = DWaveSolver(
>         4,
>         10,
>         [
>             (456, 320),
>             (228, 0),
>             (912, 0),
>             (0, 80),
>             (114, 80),
>             (570, 160),
>             (798, 160),
>             (342, 240),
>             (684, 240),
>             (570, 400),
>             (912, 400),
>             (114, 480),
>             (228, 480),
>             (342, 560),
>             (684, 560),
>             (0, 640),
>             (798, 640),
>         ],
>         [
>             (1, 6, 5),
>             (2, 10, 6),
>             (4, 3, 4),
>             (5, 9, 2),
>             (7, 8, 7),
>             (15, 11, 4),
>             (13, 12, 6),
>             (16, 14, 4),
>         ],
>         True,
>         True,
>         sampler=LeapHybridCQMSampler(),
>     )
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/55768934/322055054-e2154dbd-4579-4e30-8c6a-c6c91c315f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyOTMwOTksIm5iZiI6MTcxMzI5Mjc5OSwicGF0aCI6Ii81NTc2ODkzNC8zMjIwNTUwNTQtZTIxNTRkYmQtNDU3OS00ZTMwLThjNmEtYzZjOTFjMzE1ZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE4Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMzUwMmI4ZDQwY2NiNjI3OGMxYzJkMjFiZWU1ZTMxYTYzNzliOTNiOTNjM2ZmOTFkOGIxN2U3MGIzMGM2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YzP0nm_gZZ-PGkzX1CKo94SuQNgKaaR35fVAWTKH31s)

following this, I managed to solve it by increasing time limit to 10s

![image](https://github.com/BrunoRosendo/master-thesis/assets/55768934/1078578e-e7b1-4512-ae07-272fadd994aa)

**Comment by BrunoRosendo** [comment]
This is an example of a very complex problem (and the solution returned by dwave hybrid 10secs)

```python
cvrp = DWaveSolver(
        6,
        15,
        [
            (456, 320),
            (228, 0),
            (912, 0),
            (0, 80),
            (114, 80),
            (570, 160),
            (798, 160),
            (342, 240),
            (684, 240),
            (570, 400),
            (912, 400),
            (114, 480),
            (228, 480),
            (342, 560),
            (684, 560),
            (0, 640),
            (798, 640),
            (456, 720),
            (0, 800),
            (912, 800),
            (228, 880),
            (684, 880),
            (342, 960),
            (798, 960),
            (114, 1040),
            (570, 1040),
        ],
        [
            (1, 6, 5),
            (2, 10, 6),
            (4, 3, 4),
            (5, 9, 2),
            (7, 8, 7),
            (15, 11, 4),
            (13, 12, 6),
            (16, 14, 4),
            (0, 6, 10),
            (5, 15, 3),
            (16, 17, 7),
            (17, 18, 5),
            (19, 18, 4),
            (20, 21, 6),
            (22, 23, 7),
            (24, 25, 3),
        ],
        True,
        True,
        sampler=LeapHybridCQMSampler(),
    )
```

![image](https://github.com/BrunoRosendo/master-thesis/assets/55768934/0dee1eff-5cb5-4558-9cd5-6961591d1691)

**Comment by BrunoRosendo** [comment]
### DWave Results

If not feasible, it's only because not all trips were satisfied, more execution time or reads should solve that

#### LeapHybridCQMSampler

| **Algorithm** | **Vars** | **Vehicles** | **Capacity** | **Locations** | **Trips** | **Feasible**       | **Time** |
|---------------|----------|--------------|--------------|---------------|-----------|--------------------|----------|
| CVRP          | 15       | 2            | _None_       | 4             | _NA_      | :white_check_mark: | 5s       |
| Multi CVRP    | 544      | 2            | [10, 8]      | 16            | _NA_      | :white_check_mark: | 5s       |
| RPP           | 30       | 2            | _None_       | 4             | 2         | :white_check_mark: | 5s       |
| RPP           | 510      | 2            | _None_       | 16            | 8         | :white_check_mark: | 5s       |
| RPP           | 1020     | 4            | 10           | 16            | 8         | :x:                | 5s       |
| RPP           | 1020     | 4            | 10           | 16            | 8         | :white_check_mark: | 10s      |
| RPP           | 5010     | 6            | 15           | 26            | 15        | :x:                | 10s      |

In general, the solutions of this sampler are really good!

#### LeapHybridSampler

The variable count is made BEFORE converting into BQM. The real number higher due to slack variables and integer encoding

| **Algorithm** | **Vars** | **Vehicles** | **Capacity** | **Locations** | **Trips** | **Feasible**       | **Time** |
|---------------|----------|--------------|--------------|---------------|-----------|--------------------|----------|
| CVRP          | 15       | 2            | _None_       | 4             | _NA_      | :white_check_mark: | 3s       |
| Multi CVRP    | 544      | 2            | [10, 8]      | 16            | _NA_      | :x:                | 3s       |
| Multi CVRP    | 544      | 2            | [10, 8]      | 16            | _NA_      | :x:                | 5s       |
| Multi CVRP    | 544      | 2            | [10, 8]      | 16            | _NA_      | :x:                | 10s      |
| Multi CVRP    | 544      | 2            | [10, 8]      | 16            | _NA_      | :x:                | 20s      |
| RPP           | 30       | 2            | _None_       | 4             | 2         | :white_check_mark: | 3s       |
| RPP           | 126      | 2            | _None_       | 8             | 4         | :white_check_mark: | 3s       |
| RPP           | 286      | 2            | 20           | 12            | 6         | :x:                | 3s       |
| RPP           | 286      | 2            | 20           | 12            | 6         | :x:                | 10s      |
| RPP           | 510      | 2            | _None_       | 16            | 8         | :x:                | 3s       |
| RPP           | 510      | 2            | _None_       | 16            | 8         | :x:                | 10s      |

In general, the performance of this sampler is much worse compared to hybrid CQM. This could be due to worse embedding or pre-processing that is done in the CQM sampler or simply due to converting the problem to BQM. I can check this in #58 

#### DWaveSampler

| **Algorithm** | **Vars** | **Vehicles** | **Capacity** | **Locations** | **Trips** | **Embedding**      | **Feasible**       | num_reads | **Time** |
|---------------|----------|--------------|--------------|---------------|-----------|--------------------|--------------------|-----------|----------|
| CVRP          | 15       | 2            | _None_       | 4             | _NA_      | :white_check_mark: | :white_check_mark: | 500       | 67ms     |
| CVRP          | 63       | 2            | _None_       | 8             | _NA_      | :white_check_mark: | :x:                | 500       | 137ms    |
| CVRP          | 63       | 2            | _None_       | 8             | _NA_      | :white_check_mark: | :x:                | 3000      | 710ms    |
| Multi CVRP    | 112      | 2            | [10, 8]      | 8             | _NA_      | :white_check_mark: | :x:                | 500       | 137ms    |
| Multi CVRP    | 544      | 2            | [10, 8]      | 16            | _NA_      | :x:                | _NA_               | _NA_      | _NA_     |
| RPP           | 30       | 2            | _None_       | 4             | 2         | :white_check_mark: | :white_check_mark: | 1000      | 115ms    |
| RPP           | 126      | 2            | _None_       | 8             | 4         | :white_check_mark: | :x:                | 1000      | 224ms    |
| RPP           | 126      | 2            | _None_       | 8             | 4         | :white_check_mark: | :x:                | 3500      | 802ms    |

The pre-processing seems to take really long or never finds a solution, probably due to embedding, something to tackle in #58
Also, there is a maximum execution time of 1s, which can be reached with some inputs. Infeasible results are probably caused by not having enough reads (increasing it would result in high execution times)

**Comment by BrunoRosendo** [comment]
IBM: I tried creating sessions with qiskit runtime, but I encountered version conflicts

```
ImportError: Qiskit is installed in an invalid environment that has both Qiskit >=1.0 and an earlier version. You should create a new virtual environment, and ensure that you do not mix dependencies between Qiskit <1.0 and >=1.0. Any packages that depend on 'qiskit-terra' are not compatible with Qiskit 1.0 and will need to be updated. Qiskit unfortunately cannot enforce this requirement during environment resolution. See https://qisk.it/packaging-1-0 for more detail.
```

https://docs.quantum.ibm.com/run/run-jobs-in-session
https://pypi.org/project/qiskit-ibm-runtime/

check the docs https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/release-notes

**Comment by BrunoRosendo** [comment]
the execution works with backendsampler, but I cannot use sessions with that

**Comment by BrunoRosendo** [comment]
Based on the comment above and the thread below, I tried transpiling the ansatz and adding a padding to the operator (observable) as to match the number of qubits in the backend. However, I can't find a way to add the padding. Even if I did, I think there would be more problems.

https://quantumcomputing.stackexchange.com/questions/29332/how-to-avoid-delays-must-be-a-multiple-of-16-samples-error-with-estimator-sa

**Comment by BrunoRosendo** [comment]
I created #81 , for now I'll wait for a potential fix on qiskit's part. For now, this issue will be **blocked**

**Comment by BrunoRosendo** [comment]
### Qiskit Results

#### No Warm Start

| **Algorithm** | **Vars** | **Vehicles** | **Capacity** | **Locations** | **Trips** | **Feasible**       | **Time** |
|---------------|----------|--------------|--------------|---------------|-----------|--------------------|----------|
| RPP          | 4       | 1            | _None_       | 2             | 1      | :x: |  21s p/ iter      |
| CVRP          | 15       | 2            | _None_       | 4             | _NA_      | :x: | 23s p/ iter       |
| Multi CVRP    | 544      | 2            | [10, 8]      | 16            | _NA_      | :x: |  39s p/ iter       |

#### Warm Start

| **Algorithm** | **Vars** | **Vehicles** | **Capacity** | **Locations** | **Trips** | **Feasible**       | **Time** |
|---------------|----------|--------------|--------------|---------------|-----------|--------------------|----------|
| RPP          | 4       | 1            | _None_       | 2             | 1      | :x: | 21 p/ iter      |
| CVRP          | 36       | 2            | _None_       | 4             | _NA_      | :x: | 23s p/ iter       |

Warm start doesn't seem to matter in execution time, at least in the examples I used


Tests with IBM-Q are extremely hard for the following reasons:
- Iterations take too long to execute, with ~21secs per iteration. For a simple problem with 4 vars (example above), this would already exceed the monthly quota (~24mins)
- Even though I'm using a session, I still need to queue every time the algorithm runs an iteration. This is extremely time-consuming. I will ask around if there is a solution since QAOA needs to adjust the parameters for each iteration.

I imagine I will only be able to run 1-2 examples for the thesis, and everything else will be done with simulators.


PS: By [this article](https://docs.quantum.ibm.com/run/sessions), the jobs are only prioritized so I don't think I have control over this.
